---

# NGINX

- name: Install Nginx
  include_role:
    name: nginxinc.nginx

# NGINX LDAP authentication

- name: Get installed Nginx version
  command:
    cmd: nginx -v
  register: get_nginx_version
  check_mode: no
  changed_when: not sequenceserver_nginx_version

- name: Set nginx_version variable
  set_fact:
    sequenceserver_nginx_version: "{{ get_nginx_version.stderr | regex_search('nginx/(?P<version>\\d+\\.\\d+\\.\\d+)', '\\g<version>') | first }}"

- name: Create directory for nginx related sources if it does not exist
  file:
    path: "{{ sequenceserver_nginx_loaded_sources_path }}"
    state: directory
    mode: '0755'

- name: Get and unarchive the nginx source (needs same version as the one installed with role nginxinc.nginx)
  unarchive:
    src: 'https://nginx.org/download/nginx-{{ sequenceserver_nginx_version }}.tar.gz'
    dest: "{{ sequenceserver_nginx_loaded_sources_path }}"
    remote_src: yes

- name: Install Git
  include_role:
    name: geerlingguy.git

- name: Get source of the nginx-ldap-auth module
  git:
    repo: 'https://github.com/kvspb/nginx-auth-ldap.git'
    dest: "{{ sequenceserver_nginx_loaded_sources_path }}/nginx-auth-ldap"
    version: 83c059b73566c2ee9cbda920d91b66657cf120b7
  register: get_ldap_auth_source

- name: Install packages required for compiling the nginx module
  package:
    state: present
    name: "{{ sequenceserver_nginx_base }}"
  when: sequenceserver_nginx_base is defined

- name: Check if the compiled nginx-ldap-auth module is already present
  stat:
    path: /etc/nginx/modules/ngx_http_auth_ldap_module.so
  register: stat_module

- name: Compile the nginx-ldap-auth module (https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/)
  command:
    chdir: "{{ sequenceserver_nginx_loaded_sources_path }}/nginx-{{ sequenceserver_nginx_version }}"
    cmd: "{{ item }}"
  with_items:
    - "./configure --with-compat --add-dynamic-module={{ sequenceserver_nginx_loaded_sources_path }}/nginx-auth-ldap"
    - make modules
  when: not stat_module.stat.exists

- name: Copy the nginx-ldap-auth module library to the nginx module directory
  copy:
    src: "{{ sequenceserver_nginx_loaded_sources_path }}/nginx-{{ sequenceserver_nginx_version }}/objs/ngx_http_auth_ldap_module.so"
    dest: /etc/nginx/modules/
    mode: 0644
    remote_src: yes

- name: Insert the load_module directive in nginx conf
  lineinfile:
    line: "load_module modules/ngx_http_auth_ldap_module.so;"
    dest: /etc/nginx/nginx.conf
    regexp: "load_module modules/ngx_http_auth_ldap_module.so;"
    insertbefore: BOF
