---

# CentOS 7 specific tasks

- name: CentOS 7 | Enable environment variable
  copy:
    src: "../files/rh-ruby25.sh"
    dest: "/etc/profile.d/rh-ruby25.sh"

- name: CentOS 7 | Create environment file for systemd
  copy:
    dest: "/opt/rh/rh-ruby25/service-environment"
    content: 'RH_RUBY25_SCLS_ENABLED="rh-ruby25"'
