---
# handlers

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Force reload systemd for Centos7
  shell:
    cmd: "systemctl daemon-reload"
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"

- name: Restart syslog service
  service:
    name: rsyslog
    state: restarted

- name: Restart changed sequenceserver services
  service:
    name: sequenceserver-{{ item.item.name }}
    state: restarted
    enabled: yes
  when: item.changed
  with_items:
    - "{{ service.results }}"
    - "{{ config.results }}"

- name: Restart all sequenceserver services
  service:
    name: sequenceserver-{{ item.name }}
    state: restarted
    enabled: yes
  with_items: "{{ sequenceserver_blast_db }}"
