---
- name: Converge
  hosts: all
  become: true
  roles:
    - abims_sbr.sequenceserver
  vars:
    sequenceserver_blast_binaries: /usr/local/anaconda/envs/blast/bin
    sequenceserver_blast_db:
      # yamllint disable-line rule:braces
      - name: 'my_db'
        port: '4567'
        path: '/tmp/test-data'
        placeholders: [{key: 'key_string', value: 'value1'}, {key: 'key_link', value: '<a href="http://testplaceholder.com">my favorite link</a>'}]
        conf_options: [{key: 'job_lifetime', value: '10080'}, {key: 'databases_widget', value: 'tree'}, {key: 'options', value: {'blastn': {'default': ['-task blastn', '-evalue 1e-5'], 'short-seq': ['-task blastn-short', '-evalue 1e-1']}}}]
    sequenceserver_top_web_page_html_path: "/tmp/top_web_page.html"
    sequenceserver_bottom_web_page_html_path: "/tmp/bottom_web_page.html"
    sequenceserver_home_url: "http://myfavoritewebsite.com"
    sequenceserver_support_email: "mailto:amazingsupport@myfavoritewebsite.com"
