---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install miniconda
      include_role:
        name: andrewrothstein.miniconda
      vars:
        miniconda_parent_dir: /usr/local
    - name: Install conda env with blast conda package
      include_role:
        name: andrewrothstein.conda-env
      vars:
        conda_env_name: blast
        conda_env_environment: tests/env.yml
        conda_env_conda_dir: /usr/local/anaconda
