---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install dependencies.
      package:
        name:
          - curl
    - name: Add user sequenceserver
      user:
        name: sequenceserver
    - name: Install miniconda
      include_role:
        name: andrewrothstein.miniconda
      vars:
        miniconda_parent_dir: /usr/local
    - name: Install conda env with blast conda package
      include_role:
        name: andrewrothstein.conda-env
      vars:
        conda_env_name: blast
        conda_env_environment: tests/env.yml
        conda_env_conda_dir: /usr/local/anaconda
    - name: Copy my_db
      copy:
        src: "{{ item }}"
        dest: /tmp/test-data/
        owner: root
        mode: 0644
      with_fileglob:
        - tests/test-data/my_db.*
    - name: Copy top_web_page.html
      copy:
        src: tests/top_web_page.html
        dest: /tmp/
        owner: root
        mode: 0644
    - name: Copy bottom_web_page.html
      copy:
        src: tests/bottom_web_page.html
        dest: /tmp/
        owner: root
        mode: 0644
    # https://github.com/geerlingguy/docker-ubuntu2004-ansible/issues/24
    - name: Set right permissions for /tmp dir, needed for apt-get update used in role nginxinc.nginx
      ansible.builtin.file:
        path: /tmp
        mode: '1777'
    - name: Install previous Nginx version, to test uninstall
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_version: =1.23.1-1~focal
    - name: Install Ruby from Ubuntu package, to test uninstall
      package:
        state: present
        name:
          - ruby-full
          - ruby-dev
