---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Test blast installation
      shell: # noqa 301 305
        cmd: "/usr/local/anaconda/envs/blast/bin/blastn -version"
      register: blast_command
      failed_when: blast_command.rc > 0
    - name: Test my_db
      shell: # noqa 301 305
        cmd: "/usr/local/anaconda/envs/blast/bin/blastdbcmd -db /tmp/test-data/my_db -entry all"
      register: blastdbcmd_command
      failed_when: blastdbcmd_command.rc > 0
    - name: Ubuntu 18 | Test SequenceServer installation
      shell: # noqa 301
        cmd: "export GEM_PATH=/usr/local/share/gems && /usr/local/share/gems/bin/sequenceserver --version"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: CentOS 7 | Test SequenceServer installation
      shell: # noqa 301
        cmd: "export GEM_PATH=/opt/rh/rh-ruby25/root/usr/local/share/gems && export RH_RUBY25_SCLS_ENABLED=rh-ruby25 && /usr/bin/scl enable rh-ruby25 -- /opt/rh/rh-ruby25/root/usr/local/bin/sequenceserver --version" # noqa 204
      when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
#    - name: Test that SequenceServer service is running for my_db
#      systemd:
#        name: sequenceserver-my_db.service
#      register: service_result
#      failed_when: service_result.status.SubState != 'running'
#    - name: Test that SequenceServer service is running for my_db
#      service_facts:
#    - name: Debug service_facts
#      debug:
#        var: ansible_facts.services
    - name: Service logs
      shell: # noqa 301 303 305
        cmd: "systemctl status sequenceserver-my_db.service"
      register: status
    - name: Display service logs
      debug:
        var: status
    - name: Test that SequenceServer service is running for my_db
      service_facts:
      failed_when: ansible_facts.services['sequenceserver-my_db.service']['state'] != 'running'
