---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Test blast installation
      shell: # noqa 301
        cmd: "/usr/local/anaconda/envs/blast/bin/blastn --version"
      register: blast_command
      failed_when: blast_command.rc > 0
#    - name: Test SequenceServer installation
#      shell: # noqa 301
#        cmd: "export PATH=$PATH:/usr/local/share/gems/bin && /usr/local/share/gems/bin/sequenceserver --version"
#      register: sequenceserver_command
#      failed_when: sequenceserver_command.rc > 0
    - name: Test that SequenceServer service is running for my_db
      systemd:
        name: sequenceserver-my_db.service
      register: service_result
      failed_when: service_result.status.SubState != 'running'
