---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Test blast installation
      shell: # noqa 301 305
        cmd: "/usr/local/anaconda/envs/blast/bin/blastn -version"
      register: blast_command
      failed_when: blast_command.rc > 0
    - name: Test my_db
      shell: # noqa 301 305
        cmd: "/usr/local/anaconda/envs/blast/bin/blastdbcmd -db /tmp/test-data/my_db -entry all"
      register: blastdbcmd_command
      failed_when: blastdbcmd_command.rc > 0
    - name: Ubuntu 18 | Test SequenceServer installation
      shell: # noqa 301
        cmd: "export GEM_PATH=/usr/local/share/gems && /usr/local/share/gems/bin/sequenceserver --version"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: Ubuntu 20 | Test SequenceServer installation
      shell: # noqa 301
        cmd: "export GEM_PATH=/usr/local/share/gems && /usr/local/share/gems/bin/sequenceserver --version"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: CentOS 7 | Test SequenceServer installation
      shell: # noqa 301
        cmd: "export GEM_PATH=/opt/rh/rh-ruby25/root/usr/local/share/gems && export RH_RUBY25_SCLS_ENABLED=rh-ruby25 && /usr/bin/scl enable rh-ruby25 -- /opt/rh/rh-ruby25/root/usr/local/bin/sequenceserver --version" # noqa 204
      when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: Get SequenceServer service logs
      slurp:
        src: "/var/log/sequenceserver/sequenceserver.log"
      register: log
    - name: Display SequenceServer service logs
      debug:
        msg: "{{ log.content | b64decode }}"
    - name: Test that SequenceServer service is running for my_db
      systemd:
        name: sequenceserver-my_db.service
      register: service_result
      failed_when: service_result.status.SubState != 'running'
    - name: Test NGINX home page
      get_url:
        url: "http://localhost"
        dest: "/tmp/nginx.html"
    - name: Get /etc/hosts file content
      slurp:
        src: "/etc/hosts"
      register: etc_hosts
    - name: Display /etc/hosts file content
      debug:
        msg: "{{ etc_hosts.content | b64decode }}"
    - name: Get listening ports
      community.general.listen_ports_facts:
        command: 'ss'
      register: listening_ports
    - name: Display listening ports
      debug:
        msg: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique | sort | list }}"
    - name: Test SequenceServer home page with curl
      shell: # noqa 301
        cmd: "curl -sL http://localhost:4567 -o /tmp/home.html"
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: Get /tmp/home.html file content
      slurp:
        src: "/tmp/home.html"
      register: etc_hosts
    - name: Display /tmp/home.html file content
      debug:
        msg: "{{ /tmp/home.html.content | b64decode }}"
    - name: Test that the SequenceServer home page is rendering the values of the placeholders set for my_db
      shell: # noqa 301
        cmd: curl -sL http://localhost:4567 | grep -q '<a href="http://testplaceholder.com">my favorite link</a>'
      register: sequenceserver_command
      failed_when: sequenceserver_command.rc > 0
    - name: Test SequenceServer home page
      get_url:
        url: "http://0.0.0.0:4567"
        dest: "/tmp/page.html"
      register: sequenceserver_page
    - name: Test that the SequenceServer home page is rendering the values of the placeholders set for my_db
      lineinfile:
        path: "{{ sequenceserver_page.dest }}"
        line: 'Render custom link for this database: <a href="http://testplaceholder.com">my favorite link</a>'
        state: present
      check_mode: yes
