---
name: CI
on: [push, pull_request]

defaults:
  run:
    working-directory: 'loraine-gueguen.sequenceserver'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'loraine-gueguen.sequenceserver'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - ubuntu1804

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'loraine-gueguen.sequenceserver'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Test SequenceServer installation
        run: > sequenceserver --version && (echo 'SequenceServer availability test: pass' && exit 0) || (echo 'SequenceServer availability test: fail' && exit 1)

      - name: Test that SequenceServer service is running for my_db
        run: > systemctl show -p SubState sequenceserver-my_db.service | grep -q 'SubState=running' && (echo 'SequenceServer service running test: pass' && exit 0) || (echo 'SequenceServer service running test: fail' && exit 1)
